### ISSUE TITLE
BTL-200

### ISSUE THREAD

**Issue by imailjohn** [D3M80L/hassio-mipow#13]
"Unable to connect" when trying to connect to BTL200, assuming non compatability.

**Comment by christianpionke1** [comment]
Same issue with an older BTL201 - "Failed to Connect." Logs show the following
Logger: custom_components.mipow.mipow
Source: custom_components/mipow/mipow.py:288
Integration: mipow ([documentation](https://github.com/D3M80L/hassio-mipow))
First occurred: 3:37:41 PM (2 occurrences)
Last logged: 3:39:48 PM
MIPOW SMART BULB: Disconnected; RSSI: -92

**Comment by D3M80L** [comment]
Hey, both devices are non-battery powered, so I assue the issue is the same. Hope to find some time next week for a fix.

**Comment by pitachx** [comment]
I've just checked on my BTL301W and it's working. 
Thank you for this fix.
